### ISSUE TITLE
How hard is it to make it work flawlessly

### ISSUE THREAD

**Issue by cesarkohl** [egm0121/jest-test-gen#17]
Hey Giulio,

This project is quite interesting. How hard is it to make it work flawlessly?

I mean, the project currently creates a great boilerplate but the ultimate goal could be to create all positive and negative tests.

I'd like to understand what are the pitfalls you have already seen :)

**Comment by egm0121** [comment]
Hi Cesar, 

Would you care to elaborate a bit longer on what you would like to include in the boilerplate that is not present at the moment? Please provide some examples

the goal of the project is to generate as much boilerplate as possible for every function / class exported from a source file
I'd say the two main goals of this tool are:

1. reduce the amount of test code that the developer needs to write as much as possible (ideally only the actual logic to ensure proper behaviour)
2. provide a boilerplate for every export and every method so that it reduces the chance of forgetting to test some of the exposed functionality.

**Comment by cesarkohl** [comment]
Hey Giulio,

My question is: how hard is to create not only the boilerplate but the full test coverage?

I'm making this quite open question so we can have some space for thinking.

**Comment by egm0121** [comment]
@cesarkohl Conceptually you cannot extrapolate unit tests implementation from parsing the source that you want to test.
Even if you were able to create tests that can cover the logic expressed in the source code, it would be impossible to catch errors this way, it would always pass by definition, and that would not be useful.
You need the developer context about what the logic should be to write tests that are meaningfully asserting whether the particular implementation in the source file behaves in a way that conforms to the desired behavior.
The closest you can get to having the actual testing logic somehow understood and some tests being generated is to use an AI approach to the testing.  There are limitations still but it is possible to pass a source file and a textual description of the requirements that this implementation must satisfy and have a LLM spit out plausible unit tests.
While that is an exciting approach it does fall outside of the scope of this tool.

**Comment by cesarkohl** [comment]
Hey Giulio,

I got your point: the tests should dictate how the code works and not the opposite way. That's why generating the test suite from the code is wrong.

In the case of using LLM, that's not a viable option IMO: AI can only suggest and not be certain of something. Since tests must be exact, the LLM output couldn't be reliable.

Interesting topic, thanks for sharing your opinion!

**Comment by egm0121** [comment]
Yeah at that point you would have to use the LLM output as a suggestion or inspiration for your own tests.. great talking to you!
